service: '${env:SERVICE_NAME_PREFIX, "inbox-api-local"}'
frameworkVersion: '3'
custom: '${file(./serverless-config/custom.yml)}'
provider: '${file(./serverless-config/provider.yml)}'
useDotenv: true
functions: '${file(serverless-config/functions.yml)}'
resources: '${file(serverless-config/resources.yml)}'
plugins: ${file(serverless-config/plugins.yml):plugins}
