service: '${env:SERVICE_NAME_PREFIX, "inbox-api-local"}'
frameworkVersion: '3'

useDotenv: true

custom:
  secretsPrefix: '/${env:SERVICE_NAME_PREFIX, "local"}'
  stage: '${opt:stage, "local"}'
  stackName: '${self:service}'
  # lambdaAccountId: "599272883479"
  # lambdaRegion: ${self:provider.region}
  # lambdaFunctionName: addMessage
  # commLambdaPrefix: "arn:aws:lambda:${self:provider.region}:${self:custom.commAccountId}:function:ssm:${self:custom.secretsPrefix}-${opt:stage}"
  # customDomain:
  #   # domainName: ${env:API_GATEWAY_CUSTOM_DOMAIN, ssm:${self:custom.secretsPrefix}/API_GATEWAY_CUSTOM_DOMAIN}
  #   # domainName: "akshaydevzone.site"
  #   # basePath: ${env:API_GATEWAY_SUFFIX, ssm:${self:custom.secretsPrefix}/API_GATEWAY_SUFFIX, "inbox-api"}
  #   stage: ${opt:stage, "local"}
  #   createRoute53Record: false
  #   createRoute53IPv6Record: false
  #   apiType: rest
  #   autoDomain: false
    # endpointType: private

provider:
  name: aws
  region: ${env:AWS_REGION, "us-east-1"}
  runtime: nodejs20.x
  endpointType: PRIVATE
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource: "*"  

plugins:
  - serverless-dotenv-plugin
  # - serverless-domain-manager
  - serverless-offline
  - serverless-esbuild

functions:
  addMessage:
    handler: src/handlers/addMessage.handler
    events:
      - http:
          path: v1/conversations/{conversationId}/messages
          method: post




