Resources:
  ApiGatewayBasePathMapping:
    Type: AWS::ApiGateway::BasePathMappingV2
    DependsOn: 
      - ApiGatewayDeployment${sls:instanceId}
    Properties:
      RestApiId: 
        Ref: ApiGatewayRestApi
      Stage: ${opt:stage, "local"}
      BasePath: ${self:custom.apiGatewaySuffix}
      DomainNameArn: ${self:custom.apiGatewayDomainArn}
